// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __scvxclustr_h__
#define __scvxclustr_h__

#include "scvxclustr_RcppExports.h"

#endif // __scvxclustr_h__
