# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm_eigen <- function(X, w, gamma1, gamma2, gamma2_weight, nu, tol_abs, max_iter, type, f) {
    .Call('scvxclustr_admm_eigen', PACKAGE = 'scvxclustr', X, w, gamma1, gamma2, gamma2_weight, nu, tol_abs, max_iter, type, f)
}

ama_eigen <- function(X, w, ix, gamma1, gamma2, gamma2_weight, nu, tol_abs, max_iter, type) {
    .Call('scvxclustr_ama_eigen', PACKAGE = 'scvxclustr', X, w, ix, gamma1, gamma2, gamma2_weight, nu, tol_abs, max_iter, type)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('scvxclustr_RcppExport_registerCCallable', PACKAGE = 'scvxclustr')
})
